<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('sm_quicklogin/quicklogin.css');?>" media="all" />
<?php if (!Mage::getModel('customer/session')->isLoggedIn()):?>
    <script src="<?php echo $this->getSkinUrl('sm_quicklogin/quicklogin.js'); ?>" type="text/javascript"></script>
<div id="quicklogin" style="display: none;">
    <div class="account-login<?php if (!$this->helper('customer')->isRegistrationAllowed()) echo ' login-only'?>">
        <div class="login-message" style="color: red"></div>
        <?php echo $this->getChildHtml('customer.form.login.extra')?>
        <form action="<?php echo $this->getUrl('quicklogin/account/ajaxLogin');?>" method="post" id="login-form">
            <?php echo $this->getBlockHtml('formkey'); ?>
            <div class="fieldset">
                <div class="col1-set">
                    <div class="col-1 registered-users">
                        <ul class="form-list1">
                            <li>
                                <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                                <div class="input-box">
                                    <input name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername())?>" id="email" type="text" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                                </div>
                            </li>
                            <li>
                                <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                                <div class="input-box">
                                    <input name="login[password]" type="password" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                                </div>
                            </li>
                            <?php echo $this->getChildHtml('form.additional.info');?>
                            <li class="note">
                                <a href="<?php echo $this->getForgotPasswordUrl() ?>"><?php echo $this->__('Forgot Your Password?') ?></a>
                            </li>
                            <li class="buttons-set">
                                <button type="submit" class="button" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
                            </li>
                        </ul>
                        <span class="back-link">
                            <p><a title="Create new account?" href="javascript:createAccount()" id="popupcreate">Create new account?</a></p>
                            <p><a title="Forgot your password?" href="javascript:forgotAccount()" id="popupforgot">Forgot password?</a></p>
                        </span>
                        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                    </div>
                </div>
            </div>
        </form>

    </div>
    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
        //]]>
    </script>
</div>
<div class="register-form" style="display: none;">
    <div class="col-1 new-users">
        <div class="regis-message" style="color: red"></div>
        <form action="<?php echo $this->getUrl('quicklogin/account/ajaxRegister');?>" method="post" id="regis-form" class="frm-regis">
            <div class="content">
                <h3><?php echo $this->__('New Customers') ?></h3>
                <div class="content">
                    <ul class="form-list">
                        <li>
                            <label for="email"><?php echo $this->__('First Name') ?> <span class="required">*</span></label><br />
                            <input id="firstname" class="input-text required-entry" type="text" title="First Name" value="" name="firstname" />
                        </li>

                        <li>
                            <label for="pass"><?php echo $this->__('Last Name') ?> <span class="required">*</span></label><br />
                            <input id="lastname" class="input-text required-entry" type="text" title="Last Name" value="" name="lastname" />
                        </li>
                        <li>
                            <label for="pass"><?php echo $this->__('Email Address') ?> <span class="required">*</span></label><br />
                            <input id="email_address" class="input-text validate-email required-entry" type="text" title="Email Address" value="" name="email" />
                        </li>

                        <li>
                            <label for="pass"><?php echo $this->__('Password') ?> <span class="required">*</span></label><br />
                            <input id="password" class="input-text required-entry validate-password" type="password" title="Password" name="password"/>
                        </li>

                        <li>
                            <label for="pass"><?php echo $this->__('Confirm Password') ?> <span class="required">*</span></label><br />
                            <input id="confirmation" class="input-text required-entry validate-password" type="password" title="Password" name="confirmation"/>
                        </li>
                        <li class="control">
                            <div class="input-box">
                                <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed" />
                            </div>
                            <label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
                        </li>
                    </ul>
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                </div>

            </div>
            <div class="buttons-set">
                <button type="submit" class="action-btn"><span><?php echo $this->__('Create an Account') ?></span></button>
            </div>
        </form>
    </div>
    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('regis-form', true);
        //]]>
    </script>
</div>
<div class="forgot-form" style="display: none;">
    <div class="page-title">
        <h1><?php echo $this->__('Forgot Your Password?') ?></h1>
    </div>
    <div class="login-message" style="color: red"></div>
    <form action="<?php echo $this->getUrl('quicklogin/account/ajaxForgot');?>" method="post" id="forgot-form1">
        <div class="fieldset">
            <p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.'); ?></p>
            <ul class="form-list">
                <li>
                    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>" />
                    </div>
                </li>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
            </ul>
        </div>
        <div class="buttons-set form-buttons">
            <p class="back-link"><a href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><small>&laquo; </small><?php echo $this->__('Go back') ?></a></p>
            <button type="submit" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
        </div>
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    </form>
    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('forgot-form1', true);
        //]]>
    </script>
</div>
<?php else: ?>
<script type="text/javascript">
    jQuery('.quick-access > .links li').click(function(e){
        jQuery('.list-myaccount').slideToggle('slow');
        e.preventDefault();
    });
</script>
<div class="list-myaccount" style="display: none;">
<?php
$layout = Mage::getModel('core/layout');
$layout->getUpdate()->load('customer_account');
$layout->getUpdate()->addUpdate('
        <remove name="address_book"/>');
$layout->generateXml()->generateBlocks();

echo $layout->getBlock('customer_account_navigation')->toHtml();
?>
<?php endif; ?>
</div>